### ISSUE TITLE
Weak Passwords possible

### ISSUE THREAD

**Issue by kfrohwein** [SIWECOS/siwecos-webhostservice#8]
The sign up form should enforce a more complex password policy.

**Comment by Skeeve** [comment]
Why?

Personally I'm against forcing users to follow arbitrary rules to "strengthen" passwords. Users should decide themselves how strong or weak they want their password to be. Personally I usually follow https://www.xkcd.com/936/

What would your personal "Strengthmeter" suggest to implement?
